spring:
  profiles: eureka1
server:
  port: 8000
eureka:
  server:
    eviction-interval-timer-in-ms: 300000
  instance:
    hostname: eureka1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka1:8000/eureka
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
#      defaultZone: http://eureka2:8001/eureka,http://eureka3:8002/eureka

---

spring:
  profiles: eureka2
server:
  port: 8001
eureka:
  server:
    eviction-interval-timer-in-ms: 300000
  instance:
    hostname: eureka2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka1:8000/eureka,http://eureka3:8002/eureka

---

spring:
  profiles: eureka3
server:
  port: 8002
eureka:
  server:
      eviction-interval-timer-in-ms: 300000
  instance:
    hostname: eureka3
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka1:8000/eureka,http://eureka2:8001/eureka
